### PR TITLE
fix trigger for ghes sync

### PR DESCRIPTION
**Pull request by nickfyson**
I think this bug snuck in when [updating all the template workflows to use `$default_branch`](https://github.com/actions/starter-workflows/pull/1724).

### CODE REVIEW

**Comment by Phantsure** [comment]
Is the default branch not `main`?

**Review by Phantsure — APPROVED** [review]

**Comment by Phantsure** [comment]
Interesting. It seems to fix that

**Comment by nickfyson** [comment]
The mistake was in accidentally applying the use of a template variable inside an actual workflow. Rendering of the templates happens in the setup experience, the string `$default_branch` doesn't mean anything to Actions itself...  🙂

**Comment by Phantsure** [comment]
Thanks for that

**Pull request merged**
