### PR TITLE
Improve PHP workflow and add PHP package workflow

### LINKED ISSUE #221: Improve PHP support in starter workflows.
1) The current PHP workflow is a not of much use as it does not have any way to install extensions or customize the PHP environment. Most PHP projects have extensions as requirements which are not default.

2) Also there is no matrix workflow for testing PHP packages with different versions and supported OS.

Given these 2 reasons I want to improve the existing PHP workflow and add one with matrix workflow for PHP packages using this action [shivammathur/setup-php](https://github.com/shivammathur/setup-php). Just like other setup-* actions, I find that this provides a uniform interface to setup workflows for PHP, install extensions and customize the environment.

I know you do not accept external actions here, please consider this in case of PHP, as it does not have one tool to install extensions for all OS and it is difficult to maintain a workflow for different OS if one has to script to install extensions and keep track of them.

### PR DESCRIPTION
**Pull request by ad4g**
- Improve PHP workflow to add support for installing extensions as most PHP projects have extensions which are not default as requirements.
- Add a PHP package workflow to test PHP packages with different versions and supported OS.

I know you do not accept external actions here, but I have used [shivammathur/setup-php](https://github.com/shivammathur/setup-php) in both these workflows as PHP does not have one tool to install extensions for all OS and it is difficult to maintain a workflow for different OS if one has to script to install extensions and keep track of them. 

- [ ] Does not use an Action that isn't in the `actions` organization. Please See #221 
- [x] Does not send data to any 3rd party service except for the purposes of installing dependencies.
- [x] Does not use a paid service or product.

Fixes #221

### CODE REVIEW

**Comment by ethomson** [comment]
I'm very excited to improve PHP support!  However:

> I know you do not accept external actions here...

That's correct, we do not.  This is a hard restriction, and it's for the safety and security of the GitHub Actions platform and ecosystem.  We'd like to see improvements to the `actions/setup-php` action to support this functionality.  I'd love to see a collaboration with https://github.com/shivammathur/setup-php - that certainly seems like a sensible path forward that leverages the expertise that @shivammathur has.

But I regret that referencing actions outside the https://github.com/actions/ organization is not something that we'll include in the getting started CI workflows at the moment.

**Comment by ad4g** [comment]
@ethomson Thanks for the response.
I hope you consider this PR in the future then because in its current state the PHP Composer workflow, as I said is of limited use.

**Comment by MasterOdin** [comment]
@ethomson Given the policy changes in #451, would it be possible to update this workflow then to pin `shivammathur/setup-php` to a sha and have this be merged?

**Comment by shivammathur** [comment]
If the policy has changed and GitHub (@ethomson) would accept the PR with `shivammathur/setup-php`, I would love to create a new updated PR as per changes in #451.

The action is used [widely](https://github.com/search?o=desc&q=shivammathur%2Fsetup-php+path%3A%2F.github%2Fworkflows&s=indexed&type=Code) by the PHP community.

**Pull request closed without merging**
