### PR TITLE
fix: bearer does not upload sarif report

### PR DESCRIPTION
**Pull request by gotbadger**
When issues are found the exit code is non zero and so the github action aborts before uploading the sarif report.

This mistake was masked previously due to a bug that was fixed where exit code was not set for this type of report.

### CODE REVIEW

**Review by cfabianski — APPROVED** [review]

**Review by manos-22 — APPROVED** [review]
Best

**Comment by cfabianski** [comment]
@jtamsut is there anything else to do to get this one merged? 🙏

**Comment by griffinashe** [comment]
@cfabianski We can merge once the branch is brought up to date.

**Comment by cfabianski** [comment]
Thanks @griffinashe 🙏 
Should be ok now

**Comment by cfabianski** [comment]
@alexisabril Thanks for the review.
I've made the requested changes. Thanks again for taking the time to reviewing it and providing those feedback

**Review by alexisabril — APPROVED** [review]

**Comment by alexisabril** [comment]
@cfabianski Thank you for the updates!

**Review by Yedfree — APPROVED** [review]

**Pull request merged**
