### PR TITLE
add shiftleft code scanning workflow

### PR DESCRIPTION
**Pull request by nickfyson**
This PR open-sources the ShiftLeft workflow that is already accessible through the Code Scanning setup page.

### CODE REVIEW

**Review by DuduAgebni — APPROVED** [review]

**Review by kukulkankanpull — APPROVED** [review]
commit proposed changes

**Review by khaled-11673 — APPROVED** [review]

**Review by khaled-11673 — COMMENTED** [review]
--Ey_ioXmlCXjebeqwb2MuaxwQxd3LRAutwAD_7c8v9sDflEfDNJI1ugJOQ594xmcUosfSUZaXGNuaDQJLrKOavEPzg3UB9XkBcz1jHjModQhhC5J187UtSqfbMRS-RvprDuK8wH3FXlH8AEFz7ITJpx0SM7RS5AjIKTDNkkQwBPihvNPXWQSwB0dLsivUyZGQg

**Review by Heretique666 — COMMENTED** [review]
nickfyson/add-shiftleft-code-scanning

**Review by zinwayz — APPROVED** [review]

**Review by kukulkankanpull — APPROVED** [review]
Amend proposed changes

**Comment by kukulkankanpull** [comment]
nickfyson/add-shiftleft-code-scanning

**Comment by kukulkankanpull** [comment]
nickfyson/add-shiftleft-code-scanning

**Review by kukulkankanpull — APPROVED** [review]
Aprrove changes nickfyson/add-shiftleft-code-scanning

**Review by kukulkankanpull — CHANGES_REQUESTED** [review]
@nickfyson

**Review by kukulkankanpull — APPROVED** [review]
@nickfyson b52ecb77123d3b51eff84f39e1d261c7b85c79f4

**Review by kukulkankanpull — APPROVED** [review]
@nickfyson nickfyson/add-shiftleft-code-scanning

**Comment by kukulkankanpull** [comment]
@nickfyson nickfyson/add-shiftleft-code-scanning

**Review by kukulkankanpull — APPROVED** [review]
nickfyson/add-shiftleft-code-scanning

**Review by kukulkankanpull — CHANGES_REQUESTED** [review]
@nickfyson Review to Approve  your the man!

**Comment by kukulkankanpull** [comment]
Add every version of Node.js that is supported upstream 
`#754` opened 15 hours ago by fulldecent • Review required
Create alibabacloud.yml 
`#742` opened 13 days ago by ljinging • Review required
 2
add shiftleft code scanning workflow  code scanning new workflow
`#719` opened 29 days ago by nickfyson • Review required

**Review by kukulkankanpull — APPROVED** [review]
merge 1 commit into `main` from `nickfyson/add-shiftleft-code-scanning`
Add every version of Node.js that is supported upstream 
#754 opened 15 hours ago by fulldecent • Review required
Create alibabacloud.yml 
#742 opened 13 days ago by ljinging • Review required
 2
add shiftleft code scanning workflow  code scanning new workflow
#719 opened 29 days ago by nickfyson • Review required

**Review by kukulkankanpull — APPROVED** [review]
@nickfyson Review Required Commit proposed changes to this PR

**Comment by kukulkankanpull** [comment]
de me confirmar lo y para el  manana se lo dare con mucho gusto gracias una vez mas por su interest en Licuadoras Industriales, Manny compare from your forked action:starter kit

**Review by kukulkankanpull — APPROVED** [review]
nickfyson/add-shiftleft-code-scanning

**Review by kukulkankanpull — APPROVED** [review]

**Review by GhostDogl — APPROVED** [review]

**Review by GhostDogl — APPROVED** [review]
dokumenty/obsah/github/potvrzení změn ve vašem projektu/ index.md

**Review by Qin9fung0124 — APPROVED** [review]

**Review by kkash18 — COMMENTED** [review]
#233

**Review by kkash18 — COMMENTED** [review]
#805

**Review by longhea — APPROVED** [review]

**Review by Saray5363 — APPROVED** [review]

**Review by longhea — APPROVED** [review]

**Review by johnperez416 — APPROVED** [review]

**Review by emadami — APPROVED** [review]

**Review by jacob2442 — APPROVED** [review]

**Review by mimimi1234-1 — COMMENTED** [review]
[Hole dir Spike, damit wir noch besser per E-Mail kommunizieren können https://www.spikenow.com/](Hole dir Spike, damit wir noch besser per E-Mail kommunizieren können https://www.spikenow.com/)

**Pull request closed without merging**
