### PR TITLE
soos-dast-scan.yml update

### PR DESCRIPTION
**Pull request by SOOS-GSteen**
update text and version

### CODE REVIEW

**Comment by griffinashe** [comment]
@alexisabril Can you please review this?

**Review by alexisabril — CHANGES_REQUESTED** [review]
Hi @SOOS-GSteen,

Would you be able to swap the `@v2` for both actions in this workflow to the corresponding tags? ([Reference in PR template](https://github.com/actions/starter-workflows/blob/main/.github/pull_request_template.md?plain=1#L53))

Outside of that note, this PR looks good to come in!

**Comment by SOOS-GSteen** [comment]
> Hi @SOOS-GSteen,
> 
> Would you be able to swap the `@v2` for both actions in this workflow to the corresponding tags? ([Reference in PR template](https://github.com/actions/starter-workflows/blob/main/.github/pull_request_template.md?plain=1#L53))
> 
> Outside of that note, this PR looks good to come in!

All set - thank you!

**Comment by griffinashe** [comment]
@SOOS-GSteen - Can you please remove the notes in the PR that suggest not using git hashes if customers want automatic updates? This is against our policy on this repo.

**Comment by SOOS-GSteen** [comment]
> @SOOS-GSteen - Can you please remove the notes in the PR that suggest not using git hashes if customers want automatic updates? This is against our policy on this repo.

@griffinashe all set - thanks!

**Review by alexisabril — APPROVED** [review]

**Pull request merged**
