### PR TITLE
Fix pre-commit lints

### PR DESCRIPTION
**Pull request by SamMorrowDrums**
There is a pre-commit linter check that is failing on the default branch. I have committed and pushed these fixes to hopefully unblock CI for other developers.

https://github.com/actions/starter-workflows/pull/1869 as an example.

### CODE REVIEW

**Comment by SamMorrowDrums** [comment]
This is the wrong fix, trim trailing whitespace is the broken part.

**Review by anaarmas — APPROVED** [review]

**Review by prabakargg — COMMENTED** [review]
prabakargg

**Comment by prabakargg** [comment]
Prabakarg

**Comment by eslamgoodabstwas-crypto** [comment]
ddc250c50eb03e6c4f29ea6c5ff29311d70b7ed4God gob

**Pull request merged**
