### PR TITLE
Because That what we used for.

### PR DESCRIPTION
**Pull request by MA24th**
Check package structure and relevant paths.

### CODE REVIEW

**Comment by andymckay** [comment]
👋🏾 This command for pip installs the current directory as an editable python package. Could you explain why you'd want to do that? This would be maybe useful for projects that want to become python packages, however less so for other projects. I'm not sure this command has value for a starter workflow at this point though.

**Comment by CORONA19** [comment]
하이

**Comment by MA24th** [comment]
> 👋🏾 This command for pip installs the current directory as an editable python package. Could you explain why you'd want to do that? This would be maybe useful for projects that want to become python packages, however less so for other projects. I'm not sure this command has value for a starter workflow at this point though.

If have multi package working in same project 
And these packages in test, this should make workflow more intensity.

**Comment by andymckay** [comment]
I'd like to aim to keep the starter workflow simple and developing multiple packages in the same project seems like an unusual thing to be doing.

Thank you so much for your help, but I'd like to avoid adding complexity to this workflow.

**Pull request closed without merging**
