### PR TITLE
Update ruby.yml to use the latest release of ruby/setup-ruby

### PR DESCRIPTION
**Pull request by eregon**
https://github.com/ruby/setup-ruby/releases/tag/v1.61.0

Is it allowed to just use `uses: ruby/setup-ruby@v1` instead of a full sha nowadays in starter-workflows? (it seems so from the text below)
That seems much better.

---
- [x] This workflow must only use actions that are produced by the language or ecosystem that the workflow supports.  These actions must be [published to the GitHub Marketplace](https://github.com/marketplace?type=actions).  We recommend that these actions be referenced using the full 40 character hash of the action's commit instead of a tag.  Additionally, workflows must include the following comment at the top of the workflow file:
    ```
    # This workflow uses actions that are not certified by GitHub.
    # They are provided by a third-party and are governed by
    # separate terms of service, privacy policy, and support
    # documentation.
    ```

### CODE REVIEW

**Comment by joshmgross** [comment]
>Is it allowed to just use uses: ruby/setup-ruby@v1 instead of a full sha nowadays in starter-workflows?

We're still determining how we want to handle this, let's stick to the full SHA for now.

**Review by joshmgross — APPROVED** [review]

**Comment by dentarg** [comment]
@joshmgross I noticed that the documentation site is using the `v1` tag instead of the full SHA: https://docs.github.com/en/actions/guides/building-and-testing-ruby#specifying-the-ruby-version. Perhaps it could be changed here too?

**Comment by joshmgross** [comment]
> @joshmgross I noticed that the documentation site is using the `v1` tag instead of the full SHA: https://docs.github.com/en/actions/guides/building-and-testing-ruby#specifying-the-ruby-version. Perhaps it could be changed here too? (EDIT: it has both, missed that)

Feel free to open an issue in https://github.com/github/docs

**Comment by eregon** [comment]
@dentarg It'd be great to update the examples in the docs based on the changes in https://github.com/actions/starter-workflows/pull/766, notably `bundler-cache: true`, if you have some time.

**Pull request merged**
