### PR TITLE
Add PowerShell / Pester workflow

### PR DESCRIPTION
**Pull request by potatoqualitee**
I understand you are not adding new workflows at this time, but I believe PowerShell was overlooked in the original documentation, which is a common problem in our community. Fortunately, PowerShell was not looked over in the runners 🤩

GitHub documentation just went public, I am updating GitHub Action Documentation with a PowerShell example. This workflow will help me create more complete documentation for the community. GitHub has provided runners with PowerShell's testing framework, Pester, built-in and accepting this pull request will help complete the documentation for my proposed PR for adding sample.

In the workflow and properties files:

- [x] The workflow filename of CI workflows should be the name of the language or platform, in lower case.  Special characters should be removed or replaced with words as appropriate (for example, "dotnet" instead of ".NET").

  The workflow filename of publishing workflows should be the name of the language or platform, in lower case, followed by "-publish".
- [x] Includes a matching `ci/properties/*.properties.json` file.
- [x] Use sentence case for the names of workflows and steps, for example "Run tests".
- [x] The name of CI workflows should only be the name of the language or platform: for example "Go" (not "Go CI" or "Go Build")
- [x] Include comments in the workflow for any parts that are not obvious or could use clarification.
- [x] CI workflows should run on `push` to `branches: [ $default-branch ]` and `pull_request` to `branches: [ $default-branch ]`.
- [ ] Packaging workflows should run on `release` with `types: [ created ]`.

Some general notes:

- [x] This workflow must only use actions that are produced by GitHub, [in the `actions` organization](https://github.com/actions), **or**
- [x] This workflow must only use actions that are produced by the language or ecosystem that the workflow supports.  These actions must be [published to the GitHub Marketplace](https://github.com/marketplace?type=actions).  Workflows using these actions must reference the action using the full 40 character hash of the action's commit instead of a tag.  Additionally, workflows must include the following comment at the top of the workflow file:
    ```
    # This workflow uses actions that are not certified by GitHub.
    # They are provided by a third-party and are governed by
    # separate terms of service, privacy policy, and support
    # documentation.
    ```
- [x] This workflow must not send data to any 3rd party service except for the purposes of installing dependencies.
- [x] This workflow must not use a paid service or product.

### CODE REVIEW

**Review by JNoppers — APPROVED** [review]

**Comment by andymckay** [comment]
Thank you @potatoqualitee but it still holds that we aren't accepting new community workflows at this time as per #631

**Comment by potatoqualitee** [comment]
@andymckay - I am happy to leave this PR open until community workflows are accepted 👍

**Comment by maciej19861317** [comment]
Racja

**Comment by potatoqualitee** [comment]
Do I just recreate this or?

**Pull request closed without merging**
