### PR TITLE
nix: add Nix action

### PR DESCRIPTION
**Pull request by domenkozar**
Please **add to this description** at the bottom :point_down:

- [x] A good description of the workflow at the bottom of this page.
- [x] Some links to the language or tool will be nice (unless its really obvious)

In the workflow and properties files:

- [x] The workflow filename of CI workflows should be the name of the language or platform, in lower case.  Special characters should be removed or replaced with words as appropriate (for example, "dotnet" instead of ".NET").

  The workflow filename of publishing workflows should be the name of the language or platform, in lower case, followed by "-publish".
- [x] Includes a matching `ci/properties/*.properties.json` file.
- [x] Use sentence case for the names of workflows and steps, for example "Run tests".
- [x] The name of CI workflows should only be the name of the language or platform: for example "Go" (not "Go CI" or "Go Build")
- [x] Include comments in the workflow for any parts that are not obvious or could use clarification.
- [x] CI workflows should run on `push` to `branches: [ master ]` and `pull_request` to `branches: [ master ]`.
- [x] Packaging workflows should run on `release` with `types: [ created ]`.

Some general notes:

- [ ] This workflow must only use actions that are produced by GitHub, [in the `actions` organization](https://github.com/actions), **or**
- [x] This workflow must only use actions that are produced by the language or ecosystem that the workflow supports.  These actions must be [published to the GitHub Marketplace](https://github.com/marketplace?type=actions).  Workflows using these actions must reference the action using the full 40 character hash of the action's commit instead of a tag.  Additionally, workflows must include the following comment at the top of the workflow file:
    ```
    # This workflow uses actions that are not certified by GitHub.
    # They are provided by a third-party and are governed by
    # separate terms of service, privacy policy, and support
    # documentation.
    ```
- [x] This workflow must not send data to any 3rd party service except for the purposes of installing dependencies.
- [x] This workflow must not use a paid service or product.

---

Adds [Nix](nixos.org/) support. This allows people to quickly setup any project that uses Nix.

On top of that it integrates with a Cachix free service (for public repositories) for saving build time via binary caching.

### CODE REVIEW

**Comment by andymckay** [comment]
We've got a starter workflow over here: https://github.com/actions/starter-workflows/pull/605 and I suspect we could do with one instead of two. A couple of things:
* This workflow won't work out of the box because of the secret, do we need to have that?
* What license is the nix logo under, this repository is under the MIT license https://github.com/actions/starter-workflows/blob/main/LICENSE

**Comment by andymckay** [comment]
One more, from the pull request template 👇🏾 

This workflow must only use actions that are produced by the language or ecosystem that the workflow supports. These actions must be published to the GitHub Marketplace. Workflows using these actions must reference the action using the full 40 character hash of the action's commit instead of a tag. Additionally, workflows must include the following comment at the top of the workflow file:

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

**Comment by domenkozar** [comment]
> This workflow won't work out of the box because of the secret, do we need to have that?

Technically it will work without cachix-action, but each PR will build everything from scratch.

That action makes sure that no unnecessary builds happen (sadly we can't use the cache action).

> What license is the nix logo under, this repository is under the MIT license https://github.com/actions/starter-workflows/blob/main/LICENSE

https://github.com/NixOS/nixos-homepage/commit/525ade227e23f2b54975021553eeb3c6b57c04bd

**Review by andymckay — APPROVED** [review]
Cool thanks @domenkozar

**Review by Newman1515 — APPROVED** [review]
Ya

**Pull request merged**
