### PR TITLE
Use $default-branch token

### PR DESCRIPTION
**Pull request by cschleiden**
This updates the existing starter workflows to use the new `$default-branch` token instead of hard-coded `master`.

### CODE REVIEW

**Comment by endolith** [comment]
This doesn't work for me.  When I commit this change, the tests no longer trigger at all.  Are we supposed to manually replace this with `master`, or is it supposed to work automatically?  I checked and it says 

> The default branch is set to `master`.

**Comment by cschleiden** [comment]
@endolith 
This only works for [workflow templates(https://docs.github.com/en/actions/configuring-and-managing-workflows/sharing-workflow-templates-within-your-organization), not for workflows.

**Comment by endolith** [comment]
ohhh, so the workflow is generated _from_ this, not actually a copy of it?

**Comment by cschleiden** [comment]
It's a copy, but *during* the copy process the `$default-branch` variable is replaced with the default branch name of the target repository.

**Comment by 256SHA** [comment]
Negative

**Comment by iAMnormztwizedumz** [comment]
Upon entering unlicenced right, so with just DIR only master is given, an option of numbers as per DIR explains.

**Comment by bjornstar** [comment]
This is a bit confusing.

These "workflow templates" should be clearly labelled as "workflow templates" otherwise people (like me) will copy them and try to use them *as is*. Is this a repository full of workflows or workflow templates? It seems like we've had the old switcheroo pulled on us here.

**Pull request merged**
