### PR TITLE
Added support for PHP and Laravel

### PR DESCRIPTION
**Pull request by svikramjeet**
Added ci/php.yml for php support :)

### CODE REVIEW

**Comment by svikramjeet** [comment]
@mscoutermarsh : Please review

**Comment by andymckay** [comment]
👋 Thanks @svikramjeet for this pull request. I note we've got a PR for PHP in #88 and that doesn't include Laravel. Also hello @christeredvartsen for that PR.

I'm a little concerned about the complexity in the Laravel template, there's a lot to do there for the end user is there anyway to make this simpler?

At this point I'd ❤️ to see one PHP template land in Actions. But I'm not an expert on PHP and would like to see either #88 land or this one. I notice that one uses `composer run-script` where as this uses `./vendor/bin/phpunit --color=always` and I'm not sure which one is more likely to work and be supported out of the box.

**Comment by svikramjeet** [comment]
Thanks @andymckay for your time, yes i can see #88 , We can use alias in composer to run scripts with composer like `composer run-script tes` and `./vendor/bin/phpunit` will work exactly same if `` alias id defined as `"test": "vendor/bin/phpunit"` in composer.json but i have added `./vendor/bin/phpunit` for simplicity

**Comment by svikramjeet** [comment]
@andymckay  I have removed the `--color=always1 hope everything will be clear now, I happy to make it even simpler by removing test cases but generally i usually found it important

**Comment by christeredvartsen** [comment]
In my opinion it does not make sense to use a specific PHP framework (Laravel) in a generic PHP starter workflow. I think it would make more sense to have a generic one that does not use any specific frameworks and perhaps a couple of more specific templates, for instance one for Laravel and one for Symfony.

> I notice that one uses composer run-script where as this uses ./vendor/bin/phpunit --color=always and I'm not sure which one is more likely to work and be supported out of the box.

When using `vendor/bin/phpunit` directly the project is required to have a dependency to `phpunit/phpunit`. When running `composer run-script test` the developer has to implement that script within `composer.json`, referencing whatever testing framework (s)he uses.

PHPUnit *is* the most used testing framework for PHP, but I wanted to have the starter workflow as generic as possible, which is why I used `run-script`.

**Comment by svikramjeet** [comment]
@christeredvartsen : I haven't used the specific config which will only work in Laravel as laravel is one of the framework which uses composer which can be used by php only applications and other frameworks.Yes PHPUnit is common testing framework and in either case we need to run composer to install the dependencies which must be present in vendor directory after running `composer install`

**Comment by christeredvartsen** [comment]
The template uses `artisan` which is the command-line interface included with Laravel.

**Comment by svikramjeet** [comment]
I am talking about PHP related yaml,  yes laravel is using artisan and i have added that as well

**Comment by christeredvartsen** [comment]
My bad, I didn't see you had multiple workflows, I only saw the Laravel one.

**Comment by svikramjeet** [comment]
No issues , Thanks for update :)

**Comment by andymckay** [comment]
Thank you @svikramjeet we've merged the PHP and Laravel ones, so although they are slightly different from yours, they are now landed so users will be able to use those. Thank you 🙇 for your help.

**Pull request closed without merging**
