### PR TITLE
Prepare python-package.yml for python 3.10

### PR DESCRIPTION
**Pull request by boxed**
Python 3.10 is coming soon, and this will cause problems with the code as currently written. The python versions are written as floats and not strings, which will mean that 3.10 == 3.1, which is going to be very surprising.

### CODE REVIEW

**Review by sohoskool — APPROVED** [review]
Approve changes

**Review by sohoskool — APPROVED** [review]
Approved

**Review by sohoskool — CHANGES_REQUESTED** [review]
Request and Approve Changes

**Review by andymckay — APPROVED** [review]
Thank you 🙇🏾 In YAML `3.1` will be the same as `3.10` so that makes sense we should make them strings 👍🏾

**Pull request merged**
