### PR TITLE
feat(pages): vitejs workflow

### PR DESCRIPTION
**Pull request by abernier**
I'm contributing my Vite.js Pages workflow.

I have this fully functional on https://github.com/abernier/tpl-react/actions/runs/3479953534

deployed here: https://abernier.github.io/tpl-react/

### CODE REVIEW

**Comment by abernier** [comment]
I started from https://github.com/actions/starter-workflows/blob/main/pages/nextjs.yml and have adapted it to Vite

NB: maybe `actions/cache` is missing, but I was not sure of the `.next/cache` folder equivalent...

**Comment by Phantsure** [comment]
@yoannchaudet Kindly review this.

**Comment by abernier** [comment]
+ have applied https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ in 93f6cdcd6482788cef12b3ae245013606dca3a70

**Comment by abernier** [comment]
reviewing seems stuck, can we request someone else available: it should be pretty quick because this pr is really small and limited

thank you

**Review by Sevdasezen — APPROVED** [review]

**Pull request closed without merging**
