### PR TITLE
Update cosign-installer to v3.5.0 in docker-publish.yml

### PR DESCRIPTION
**Pull request by TK221**
Updating cosign-installer to v3.5.0 with the default cosign version of v2.2.4, resulting in no more signing errors.
https://blog.sigstore.dev/tuf-root-update/

### CODE REVIEW

**Review by kj800x — COMMENTED** [review]
This change fixed my build. Thank you

**Comment by invince** [comment]
Fix works, great job

**Review by curlew — APPROVED** [review]
Worked for me, thanks

**Comment by kj800x** [comment]
Hi @yoannchaudet @JamesMGreene @alexisabril, sorry to cold tag like this, but what is the process for getting a PR like this reviewed and merged?

Newly generated docker publish workflows fail because they need this fix. It would be valuable to get this merged.

**Review by Eason-S-Lu — CHANGES_REQUESTED** [review]
Request an update to 3.5.0 and drop the "with" section.

**Review by Eason-S-Lu — APPROVED** [review]
Thank you so much, I hope they merge this PR.
        Eason

**Comment by jsoref** [comment]
@TK221 the description no longer matches the change (the title says 2.2.3, the description 3.4.0, but the change is to 3.5.0).

@thyeggman ignoring the above, is anything blocking this?

**Comment by TK221** [comment]
Already updated with PR: #2414.
Closing this because it is now obsolete.

**Pull request closed without merging**
