### PR TITLE
Update setup-ruby to the latest release

### PR DESCRIPTION
**Pull request by 0atman**
The default github action ruby template references **a 2-year old commit** which doesn't have any modern rubies https://github.com/ruby/setup-ruby/commit/473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e

Related: https://github.com/ruby/setup-ruby/issues/319

### Solution
We fixed this by updating the pinned version to the latest release https://github.com/alphagov/forms-api/pull/3/commits/e3c8ad2759088a12ba9f3040d2c47c23799c8455

I think that this template should either be unpinned to just v1, or regularly updated to the latest `setup-ruby` release hash.

Thank you!

---

# Example failure of the out-of-the-box user experience

### the link to the log of a failed workflow job
https://github.com/alphagov/forms-api/runs/6093152207?check_suite_focus=true

### the command and output of the step failing
```shell
Run ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
​Error: Unknown version 3.0.3 for ruby on ubuntu-20.04
        available versions for ruby on ubuntu-20.04: 2.1.9, 2.2.10, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.3.6, 2.3.7, 2.3.8, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.4.5, 2.4.6, 2.4.7, 2.4.9, 2.4.10, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.5.4, 2.5.5, 2.5.6, 2.5.7, 2.5.8, 2.6.0, 2.6.1, 2.6.2, 2.6.3, 2.6.4, 2.6.5, 2.6.6, 2.7.0, 2.7.1, 2.7.2, 3.0.0-preview1, 3.0.0-preview2, 3.0.0-rc1, 3.0.0, head, debug
        File an issue at https://github.com/ruby/setup-ruby/issues if would like support for a new version

### CODE REVIEW

**Review by Phantsure — COMMENTED** [review]
@0atman This sha doesn't look right. Can you check it once?

**Comment by 0atman** [comment]
Our actions are passing with ruby-setup sha `2b019609e2b0f1ea1a2bc8ca11cb82ab46ada124`

**Comment by Phantsure** [comment]
> Our actions are passing with ruby-setup sha `2b019609e2b0f1ea1a2bc8ca11cb82ab46ada124`

This seems the correct sha. The PR has a different sha mentioned, i.e. `e3c8ad2759088a12ba9f3040d2c47c23799c8455`. There might be some confusion.

**Comment by 0atman** [comment]
There was some confusion! My apologies, that was the sha of my commit to our own codebase :sweat_smile: Thank you for spotting that!

**Review by Phantsure — APPROVED** [review]
simple bump. Looks good to me 🚀

**Comment by farahmandakbar** [comment]
> The default github action ruby template references **a 2-year old commit** which doesn't have any modern rubies https://github.com/ruby/setup-ruby/commit/473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
> 
> Related: https://github.com/ruby/setup-ruby/issues/319
> 
> ### Solution
> We fixed this by updating the pinned version to the latest release https://github.com/alphagov/forms-api/pull/3/commits/e3c8ad2759088a12ba9f3040d2c47c23799c8455
> 
> I think that this template should either be unpinned to just v1, or regularly updated to the latest `setup-ruby` release hash.
> 
> Thank you!
> 
> ---
> 
> # Example failure of the out-of-the-box user experience
> 
> ### the link to the log of a failed workflow job
> https://github.com/alphagov/forms-api/runs/6093152207?check_suite_focus=true
> 
> ### the command and output of the step failing
> ```shell
> Run ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
> ​Error: Unknown version 3.0.3 for ruby on ubuntu-20.04
>         available versions for ruby on ubuntu-20.04: 2.1.9, 2.2.10, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.3.6, 2.3.7, 2.3.8, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.4.5, 2.4.6, 2.4.7, 2.4.9, 2.4.10, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.5.4, 2.5.5, 2.5.6, 2.5.7, 2.5.8, 2.6.0, 2.6.1, 2.6.2, 2.6.3, 2.6.4, 2.6.5, 2.6.6, 2.7.0, 2.7.1, 2.7.2, 3.0.0-preview1, 3.0.0-preview2, 3.0.0-rc1, 3.0.0, head, debug
>         File an issue at https://github.com/ruby/setup-ruby/issues if would like support for a new version

github-actions-demo.yml

**Comment by 0atman** [comment]
@farahmandakbar please explain?

**Pull request merged**
