### PR TITLE
branches: [ `$default-branch` ]

### PR DESCRIPTION
**Pull request by austenstone**
This regex `^(?!.*(default-branch)).*branches:.*` should help find anything not using [$default-branch](https://github.blog/changelog/2020-07-22-github-actions-better-support-for-alternative-default-branch-names/).

### CODE REVIEW

**Comment by Phantsure** [comment]
@austenstone What is the reasoning behind this change?

**Comment by austenstone** [comment]
> @austenstone What is the reasoning behind this change?

I was researching the $default-branch macro and figured I'd update the starter workflows based on the blog post

> We have updated all of our [starter workflows](https://github.com/actions/starter-workflows) to use a new $default-branch macro rather than the previously hardcoded master.

**Review by lukins — COMMENTED** [review]
Skvělé

**Review by Phantsure — APPROVED** [review]
Change looks aligned with the blog referred. We should have this in guidelines as well for future actions.

**Pull request merged**
