### PR TITLE
add android native codecov workflow

### PR DESCRIPTION
**Pull request by wise4rmgod**
added codecov Android native workflow

This repository contains configuration for what users see when they click on the `Actions` tab and the setup page for Code Scanning.

It is not:
* A playground to try out scripts
* A place for you to create a workflow for your repository

---

**Please note that at this time we are only accepting new starter workflows for Code Scanning. Updates to existing starter workflows are fine.**

---

In the workflow and properties files:

- [ ] The workflow filename of CI workflows should be the name of the language or platform, in lower case.  Special characters should be removed or replaced with words as appropriate (for example, "dotnet" instead of ".NET").

  The workflow filename of publishing workflows should be the name of the language or platform, in lower case, followed by "-publish".
- [ ] Includes a matching `ci/properties/*.properties.json` file.
- [ ] Use sentence case for the names of workflows and steps, for example "Run tests".
- [ ] The name of CI workflows should only be the name of the language or platform: for example "Go" (not "Go CI" or "Go Build")
- [ ] Include comments in the workflow for any parts that are not obvious or could use clarification.
- [ ] CI workflows should run on `push` to `branches: [ $default-branch ]` and `pull_request` to `branches: [ $default-branch ]`.
- [ ] Packaging workflows should run on `release` with `types: [ created ]`.
- [ ] Code Scanning workflows should run on `push` to `branches: [ $default-branch, $protected-branches ]` and `pull_request` to `branches: [ $default-branch ]`. We also recommend a `schedule` trigger of `cron: $cron-weekly`.

Some general notes:

- [ ] This workflow must only use actions that are produced by GitHub, [in the `actions` organization](https://github.com/actions), **or**
- [ ] This workflow must only use actions that are produced by the language or ecosystem that the workflow supports.  These actions must be [published to the GitHub Marketplace](https://github.com/marketplace?type=actions).  We recommend that these actions be referenced using the full 40 character hash of the action's commit instead of a tag.  Additionally, workflows must include the following comment at the top of the workflow file:
    ```
    # This workflow uses actions that are not certified by GitHub.
    # They are provided by a third-party and are governed by
    # separate terms of service, privacy policy, and support
    # documentation.
    ```
- [ ] Automation and CI workflows should not send data to any 3rd party service except for the purposes of installing dependencies.
- [ ] Automation and CI workflows cannot be dependent on a paid service or product.

### CODE REVIEW

**Comment by andymckay** [comment]
👋🏾 Hi there, this looks like its adding a new workflow and https://github.com/actions/starter-workflows/issues/631 is about why we aren't. There could be a valid exception for this though, could please give us some details if you think it is? Otherwise we'll close this pull request target.

**Comment by wise4rmgod** [comment]
This is a new workflow that will send Android native code coverage to codecov platform, I found it difficult before I got it to work and I know others will also face the same faith if it's not within their reach.
Thanks

**Comment by andymckay** [comment]
Thanks for the context @wise4rmgod, taking the time to do this and shae the workflow, but based on #631, we won't be merging this workflow. Sorry about that 🙇🏾

**Comment by RMKoRn** [comment]
User Agent Info - WhatIsMyIP.com®

Mozilla/5.0 (Linux; Android 9; SM-J737V) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.111 Mobile Safari/537.36

Screen Resolution

320×569

This page displays your User Agent String and Screen Resolution. This is a very basic output of the User Agent also referred to as simply UA. Your User Agent tells every site your visit what browser you're using. Sites are able to detect your UA and redirect to a more fitting page for your browser if desired. In other words, if you go to a site with this detection in place from a mobile phone the site might detect you are a mobile user via the UA and redirect you to their mobile site if available. This doesn't work on all sites becuase not all sites have UA detection in place. We have it built in to WhatIsMyIP.com. We detect most mobile phones and redirect them to our mobile page however, if you go to WhatIsMyIP.com from a desktop computer, you'll get redirected to the What Is My IP homepage.
UAs also tell the sites you're visiting some browser related software which you may have installed. For example, this UA (Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.0; Trident/4.0; GTB6; Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1) ; SLCC1; .NET CLR 2.0.50727; Media Center PC 5.0; InfoPath.2; .NET CLR 3.5.21022; .NET CLR 1.1.4322; .NET CLR 3.5.30729; OfficeLiveConnector.1.3; OfficeLivePatch.0.0;) tells us that the visitor is using Intern.et Explorer 8, Windows Vista, has Media Center PC 5.0 installed, Office Live Connector, etc. So if we had a special section for Vista users, we could redirect this person based on the Windows NT 6.0 string to a sub section in our site related strictly to Vista. This User Agent on the other hand, Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US; rv:1.9.1.3) Gecko/20090824 Firefox/3.5.3 tells us the visitor is using FireFox 3.5.3 and Windows Vista. Not much else.
Having the knowledge from above, User Agent Spoofing is used by many programmers that don't want people to know how they're getting to the site(s). Some programmers will find legitimate UAs and program their script to use such UAs. UAs can be blank, or contain custom information like a URL to a site that might promote a particular browser jor script.

**Review by RMKoRn — APPROVED** [review]

**Review by RMKoRn — APPROVED** [review]
I'm new to GitHub and I don't know what I'm doing all I know is that my device is compromised my understanding is they're using a  RAT REMOTE ADMINISTRATIVE TOOLS AND ARE CONTROLLING MY DEVICE THEY'VE GAINED ACCESS TO MY MICROSOFT ACCOUNT GOOGLE ACCOUNTS FACEBOOK AND REDIRECT MY GMAILS I'M JUST LOOKING FOR SOME HELP AND ADVICE I WANT TO LEARN HOW THIS WORKS THANK YOU IN ADVANCE SINCERELY
RMKoRn

**Pull request closed without merging**
