### PR TITLE
Fix the missing `on` trigger for AKS Kompose

### PR DESCRIPTION
**Pull request by bishal-pdMSFT**
Trigger spec is missing from AKS kompose starter workflow and that even shows up as error in the workflow editor.

### CODE REVIEW

**Comment by bishal-pdMSFT** [comment]
@jaiveerk @imiller31 please review the PR as you were the last committers.
cc @qpetraroia

**Review by jaiveerk — APPROVED** [review]

**Comment by bishal-pdMSFT** [comment]
@Phantsure can you please check this PR?

**Review by OliverMKing — APPROVED** [review]

**Review by davidgamero — APPROVED** [review]
lgtm

**Review by Phantsure — APPROVED** [review]
Lgtm

**Pull request merged**
