### PR TITLE
fix(openshift): comment out dangling dependency

### LINKED ISSUE #2385: OpenShift workflow doesn't work out of the box
#1564 added a workflow for `Red Hat CodeReady Dependency Analytics`, but it also broke the OpenShift workflow.

I used https://github.com/check-spelling-sandbox/starter-workflows-openshift-is-broken-1/actions/new?category=none&query=openshift and added the workflow.

You can see that it's broken:
https://github.com/check-spelling-sandbox/starter-workflows-openshift-is-broken-1/actions/runs/8841706172

image

The *comment* here does not match the *code*:
https://github.com/actions/starter-workflows/blob/2435e576016b3fdd46574a49126d65bfd0d4872f/deployments/openshift.yml#L63-L74

### PR DESCRIPTION
**Pull request by jsoref**
Fixes #2385 by making the code match the comment...

### CODE REVIEW

**Comment by jsoref** [comment]
cc: @divyansh42

**Review by divyansh42 — APPROVED** [review]

**Comment by divyansh42** [comment]
@jsoref apologies for the delay.
Could you please rebase the PR?

**Comment by Findrown** [comment]
Dangling dependency

**Comment by jsoref** [comment]
@divyansh42: you don't appear to be a member of this org, and there aren't any conflicts, is there a reason I should rebase?

**Comment by divyansh42** [comment]
@jsoref It is not allowing me to merge. It says `This branch is out-of-date with the base branch`

**Comment by divyansh42** [comment]
@jsoref unfortunately I don't know anyone who can help us in this.

**Comment by jsoref** [comment]
@thyeggman?

**Review by thyeggman — APPROVED** [review]

**Pull request merged**
