### PR TITLE
Use actions/setup-node v2

### PR DESCRIPTION
**Pull request by pastelmind**
Since actions/setup-node v2 has been declared stable since [v2.1.4](https://github.com/actions/setup-node/releases/tag/v2.1.4) (released on 2020-12-16), it should be safe to move everyone to v2.

### CODE REVIEW

**Comment by AverageComet250** [comment]
This looks fine, just update your fork.

**Comment by pastelmind** [comment]
> This looks fine, just update your fork.

Thak you, and I updated it just now.

**Review by AverageComet250 — APPROVED** [review]

**Review by andymckay — APPROVED** [review]
Thank you for updating this.

**Comment by pastelmind** [comment]
@andymckay Great! If this has been integrated, can I close this PR?

Incidentally, I don't see the "Delete Branch" button that usually pops up once a maintainer accepts a PR. Has this been merged into `main`?

**Pull request merged**
