### PR TITLE
Switch java distribution from 'adopt' to 'temurin'

### PR DESCRIPTION
**Pull request by WtfJoke**
The jdk distribution adoptopenjdk (adopt) is rebranded into eclipse adoptium (temurin), see https://blog.adoptopenjdk.net/2021/03/transition-to-eclipse-an-update/

If im not mistaken, I dont need to apply to the Github Technology Partner as this is only an update to existing workflows. I also think that most of the checkbox probably doesnt apply to this PR. 

Let me know if I should change something.

## Pre-requisites

- [N/A] Prior to submitting a new workflow, please apply to join the GitHub Technology Partner Program: [partner.github.com/apply](https://partner.github.com/apply?partnershipType=Technology+Partner).

---

### **Please note that at this time we are only accepting new starter workflows for Code Scanning. Updates to existing starter workflows are fine.**

---

## Tasks

**For _all_ workflows, the workflow:**

- [x] Should be contained in a `.yml` file with the language or platform as its filename, in lower, [_kebab-cased_](https://en.wikipedia.org/wiki/Kebab_case) format (for example, [`docker-image.yml`](https://github.com/actions/starter-workflows/blob/main/ci/docker-image.yml)).  Special characters should be removed or replaced with words as appropriate (for example, "dotnet" instead of ".NET").
- [x] Should use sentence case for the names of workflows and steps (for example, "Run tests").
- [x] Should be named _only_ by the name of the language or platform (for example, "Go", not "Go CI" or "Go Build").
- [x] Should include comments in the workflow for any parts that are not obvious or could use clarification.

**For _CI_ workflows, the workflow:**

- [x] Should be preserved under [the `ci` directory](https://github.com/actions/starter-workflows/tree/main/ci).
- [x] Should include a matching `ci/properties/*.properties.json` file (for example, [`ci/properties/docker-publish.properties.json`](https://github.com/actions/starter-workflows/blob/main/ci/properties/docker-publish.properties.json)).
- [x] Should run on `push` to `branches: [ $default-branch ]` and `pull_request` to `branches: [ $default-branch ]`.
- [x] Packaging workflows should run on `release` with `types: [ created ]`.
- [x] Publishing workflows should have a filename that is the name of the language or platform, in lower case, followed by "-publish" (for example, [`docker-publish.yml`](https://github.com/actions/starter-workflows/blob/main/ci/docker-publish.yml)).

**Some general notes:**

- [x] This workflow must _only_ use actions that are produced by GitHub, [in the `actions` organization](https://github.com/actions), **or**
- [x] This workflow must _only_ use actions that are produced by the language or ecosystem that the workflow supports.  These actions must be [published to the GitHub Marketplace](https://github.com/marketplace?type=actions).  We require that these actions be referenced using the full 40 character hash of the action's commit instead of a tag.  Additionally, workflows must include the following comment at the top of the workflow file:
    ```
    # This workflow uses actions that are not certified by GitHub.
    # They are provided by a third-party and are governed by
    # separate terms of service, privacy policy, and support
    # documentation.
    ```
- [x] Automation and CI workflows should not send data to any 3rd party service except for the purposes of installing dependencies.
- [x] Automation and CI workflows cannot be dependent on a paid service or product.

### CODE REVIEW

**Comment by beatngu13** [comment]
From the [`actions/setup-java` readme](https://github.com/actions/setup-java/blob/main/README.md):

>**NOTE:** Adopt OpenJDK got moved to Eclipse Temurin and won't be updated anymore. It is highly recommended to migrate workflows from `adopt` to `temurin` to keep receiving software and security updates. See more details in the [Good-bye AdoptOpenJDK post](https://blog.adoptopenjdk.net/2021/08/goodbye-adoptopenjdk-hello-adoptium/).

To prevent users from this (like [here](https://github.com/amaembo/streamex/pull/254#issuecomment-965028205)), this PR should be merged now.

**Comment by WtfJoke** [comment]
@laurentsimon or @nickfyson sorry for pinging you, but could you please take a look at it (I rebased it and fixed the merge conflicts).

**Review by joshmgross — APPROVED** [review]

**Comment by joshmgross** [comment]
Thanks @WtfJoke for your contribution and @beatngu13 for the extra context 🙇

**Comment by WtfJoke** [comment]
Thanks for finally merging it :D

**Review by chopperg — COMMENTED** [review]
#

**Pull request merged**
