### PR TITLE
Removes " Simulator" substring from device name.

### PR DESCRIPTION
**Pull request by bedranfleck**
Recently, `xcrun xctrace list devices 2>&1` started returning an iOS Simulator list with device names suffixed with " Simulator".
This messed up with `-destination` parameter for xcodebuild.

This pull request addresses that issue by piping sed to remove that suffix from the device name.

### CODE REVIEW

**Review by Oliver-Binns — APPROVED** [review]
Came here to fix this :D thanks for doing it!

**Review by bishal-pdMSFT — APPROVED** [review]

**Comment by bishal-pdMSFT** [comment]
@bedranfleck sorry for delayed review response. I can merge this if you are okay?

**Comment by bedranfleck** [comment]
> Came here to fix this :D thanks for doing it!

Hey, no problem! Haha, this was bugging me as well.

**Comment by bedranfleck** [comment]
> @bedranfleck sorry for delayed review response. I can merge this if you are okay?

@bishal-pdMSFT Please do! Thanks!

**Pull request merged**
