### PR TITLE
Add Phoenix starter workflow

### PR DESCRIPTION
**Pull request by jclem**
Add a Phoenix starter workflow

Phoenix is a popular web application framework for the Elixir programming language (for which we have a [starter workflow](https://github.com/actions/starter-workflows/blob/920aa0286cbaca09c2eceed9576246d6c5d38100/ci/elixir.yml)). This pull request adds a workflow similar to the Elixir workflow—the main difference is that I've added a Postgres service (Postgres is the default database for new Phoenix projects).

### Links

- [Elixir](https://elixir-lang.org)
- [Phoenix](https://www.phoenixframework.org)

### To Do

- [ ] Get SVG and understand usage rights of Phoenix logo.

---

In the workflow and properties files:

- [x] The workflow filename of CI workflows should be the name of the language or platform, in lower case.  Special characters should be removed or replaced with words as appropriate (for example, "dotnet" instead of ".NET").
- [ ] ~The workflow filename of publishing workflows should be the name of the language or platform, in lower case, followed by "-publish".~
- [x] Includes a matching `ci/properties/*.properties.json` file.
- [x] Use sentence case for the names of workflows and steps, for example "Run tests".
- [x] The name of CI workflows should only be the name of the language or platform: for example "Go" (not "Go CI" or "Go Build")
- [x] Include comments in the workflow for any parts that are not obvious or could use clarification.
- [x] CI workflows should run on `push` to `branches: [ master ]` and `pull_request` to `branches: [ master ]`.
- [ ] ~Packaging workflows should run on `release` with `types: [ created ]`.~

Some general notes:

- [x] This workflow must only use actions that are produced by GitHub, [in the `actions` organization](https://github.com/actions), **or**
- [x] This workflow must only use actions that are produced by the language or ecosystem that the workflow supports.  These actions must be [published to the GitHub Marketplace](https://github.com/marketplace?type=actions).  Workflows using these actions must reference the action using the full 40 character hash of the action's commit instead of a tag.  Additionally, workflows must include the following comment at the top of the workflow file:
    ```
    # This workflow uses actions that are not certified by GitHub.
    # They are provided by a third-party and are governed by
    # separate terms of service, privacy policy, and support
    # documentation.
    ```
- [x] This workflow must not send data to any 3rd party service except for the purposes of installing dependencies.
- [x] This workflow must not use a paid service or product.

### CODE REVIEW

**Comment by jclem** [comment]
@andymckay Do you know if a PNG will work for this? I noticed that `iconName` is just a string, so I'm curious if the rendering assumes that it will be an SVG.

**Review by tonirmv — COMMENTED** [review]
#738

**Comment by Monssif1** [comment]
مرحبا

**Comment by Monssif1** [comment]
انا جديد في هد الميدان

**Pull request closed without merging**
