### PR TITLE
Update DataDog/synthetics-ci-github-action workflow

### PR DESCRIPTION
**Pull request by AntoineDona**
This PR updates the Datadog/synthetics-ci-github-action workflow version to v1.4.0.
The release can be found here: https://github.com/DataDog/synthetics-ci-github-action/releases/tag/v1.4.0

### CODE REVIEW

**Comment by AntoineDona** [comment]
👋 Hi @felipesu19 @alexisabril ! Could I get a review for this PR? thx

**Review by alexisabril — COMMENTED** [review]
Hi @AntoineDona, thank you for the PR!

Looking at the releases for that action, it appears the hash doesn't match up. Would you verify which hash you're looking to update this to?

https://github.com/DataDog/synthetics-ci-github-action/releases

**Comment by AntoineDona** [comment]
Hi @alexisabril ! My bad, the hash is actually from the commit inside of the PR, and not the merge commit 😅
It should be good now.

**Comment by AntoineDona** [comment]
Hi @alexisabril, gentle bump on this PR!

**Review by thyeggman — APPROVED** [review]

**Comment by jameskairu** [comment]
engage

**Comment by 965022-oss** [comment]
Merge #2424 Branch: main 965022-oss-patch1/SHA 3a95482282, datadog-synthetics.yml

**Pull request merged**
