### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by fredster33**
## Pre-requisites

- [X] Prior to submitting a new workflow, please apply to join the GitHub Technology Partner Program: [partner.github.com/apply](https://partner.github.com/apply?partnershipType=Technology+Partner).
(N/A)
---

### **Please note that at this time we are only accepting new starter workflows for Code Scanning. Updates to existing starter workflows are fine.**
(N/A)
---

## Tasks

**For _all_ workflows, the workflow:**

- [X] Should be contained in a `.yml` file with the language or platform as its filename, in lower, [_kebab-cased_](https://en.wikipedia.org/wiki/Kebab_case) format (for example, [`docker-image.yml`](https://github.com/actions/starter-workflows/blob/main/ci/docker-image.yml)).  Special characters should be removed or replaced with words as appropriate (for example, "dotnet" instead of ".NET").
- [X] Should use sentence case for the names of workflows and steps (for example, "Run tests").
- [X] Should be named _only_ by the name of the language or platform (for example, "Go", not "Go CI" or "Go Build").
- [X] Should include comments in the workflow for any parts that are not obvious or could use clarification.

**For _CI_ workflows, the workflow:**

- [X] Should be preserved under [the `ci` directory](https://github.com/actions/starter-workflows/tree/main/ci).
- [X] Should include a matching `ci/properties/*.properties.json` file (for example, [`ci/properties/docker-publish.properties.json`](https://github.com/actions/starter-workflows/blob/main/ci/properties/docker-publish.properties.json)).
- [X] Should run on `push` to `branches: [ $default-branch ]` and `pull_request` to `branches: [ $default-branch ]`.
- [X] Packaging workflows should run on `release` with `types: [ created ]`.
- [X] Publishing workflows should have a filename that is the name of the language or platform, in lower case, followed by "-publish" (for example, [`docker-publish.yml`](https://github.com/actions/starter-workflows/blob/main/ci/docker-publish.yml)).

**For _Code Scanning_ workflows, the workflow:**

- [X] Should be preserved under [the `code-scanning` directory](https://github.com/actions/starter-workflows/tree/main/ci).
- [X] Should include a matching `code-scanning/properties/*.properties.json` file (for example, [`code-scanning/properties/codeql.properties.json`](https://github.com/actions/starter-workflows/blob/main/code-scanning/properties/codeql.properties.json)), with properties set as follows:
  - [X] `name`: Name of the Code Scanning integration.
  - [X] `organization`: Name of the organization producing the Code Scanning integration.
  - [X] `description`: Short description of the Code Scanning integration.
  - [X] `categories`: Array of languages supported by the Code Scanning integration.
  - [X] `iconName`: Name of the SVG logo representing the Code Scanning integration. This SVG logo must be present in [the `icons` directory](https://github.com/actions/starter-workflows/tree/main/icons).
- [X] Should run on `push` to `branches: [ $default-branch, $protected-branches ]` and `pull_request` to `branches: [ $default-branch ]`. We also recommend a `schedule` trigger of `cron: $cron-weekly` (for example, [`codeql.yml`](https://github.com/actions/starter-workflows/blob/c59b62dee0eae1f9f368b7011cf05c2fc42cf084/code-scanning/codeql.yml#L14-L21)).

**Some general notes:**

- [X] This workflow must _only_ use actions that are produced by GitHub, [in the `actions` organization](https://github.com/actions), **or**
- [X] This workflow must _only_ use actions that are produced by the language or ecosystem that the workflow supports.  These actions must be [published to the GitHub Marketplace](https://github.com/marketplace?type=actions).  We require that these actions be referenced using the full 40 character hash of the action's commit instead of a tag.  Additionally, workflows must include the following comment at the top of the workflow file:
    ```
    # This workflow uses actions that are not certified by GitHub.
    # They are provided by a third-party and are governed by
    # separate terms of service, privacy policy, and support
    # documentation.
    ```
- [X] Automation and CI workflows should not send data to any 3rd party service except for the purposes of installing dependencies.
- [X] Automation and CI workflows cannot be dependent on a paid service or product.

### CODE REVIEW

**Review by ScottBrenner — APPROVED** [review]

**Comment by fredster33** [comment]
Uh oh, please don't mark it as stale. It was approved already...

**Review by ScottBrenner — APPROVED** [review]

**Review by Phantsure — APPROVED** [review]
This looks good, provided checks don't fail. Could someone kindly allow the validation run check?

**Comment by Phantsure** [comment]
Can you merge base branch into your branch?

**Comment by fredster33** [comment]
@Phantsure done :)

**Comment by Phantsure** [comment]
@fredster33 Can you looking to the failing check? Thanks

**Comment by fredster33** [comment]
Hi @Phantsure , I don't think it's because of this PR :)

**Comment by Phantsure** [comment]
Error is at modified line. Are you sure it is not because this PR's change?

I see same quote mark used as used to start and end the sentence. Maybe that is the issue.

**Comment by fredster33** [comment]
I can try escaping it.

**Comment by fredster33** [comment]
@Phantsure done!

**Comment by Phantsure** [comment]
@fredster33 Seems like it is not resolved

**Review by Phantsure — CHANGES_REQUESTED** [review]
You can try changing the quotes to double as then single quote would be accepted part of string. In single quotes, backslash doesn't work in this way

**Review by Newman1515 — CHANGES_REQUESTED** [review]
Ok

**Review by Newman1515 — APPROVED** [review]
K

**Comment by Phantsure** [comment]
@fredster33 Kindly rebase or merge main in this branch. Will close it then

**Review by Phantsure — APPROVED** [review]
LGTM, needs rebasing

**Review by Newman1515 — COMMENTED** [review]
👍

**Comment by fredster33** [comment]
Done.

**Pull request merged**
