### PR TITLE
Fix- Add Execute Permissions to gradle

### PR DESCRIPTION
**Pull request by josharsh**

### CODE REVIEW

**Comment by ethomson** [comment]
This feels like a bandaid over a bigger problem: users should have the execute bit on in their repository.

**Comment by josharsh** [comment]
Hi!@ethomson I did not quite understand. I have just started learning about actions. Could you please tell me where did I go wrong?

**Comment by ethomson** [comment]
Hi @josharsh - sorry if I was unclear - this is more about the gradle wrapper scripts in the Git repository and not directly about GitHub Actions.

Users should `chmod +x gradlew && chmod +x gradlew.bat` and check that change into their repository.

Doing the `chmod` in the GitHub Actions run should then be unnecessary.

**Comment by ethomson** [comment]
I'm going to close this since the best practice is to check in the proper permissions.  Thanks again for prompting the discussion!

**Pull request closed without merging**
