### PR TITLE
Updating nextjs.yml for Next.js 14 Support

### PR DESCRIPTION
**Pull request by NPJigaK**
### Overview
https://nextjs.org/blog/next-14#other-changes
> [Breaking] next export command is deprecated in favor of output: 'export' ([Docs](https://nextjs.org/docs/app/building-your-application/deploying/static-exports))

This pull request tackles a major alteration incorporated in Next.js 14— the deprecation of the `next export` command, now supplanted by `output: 'export'` as delineated in the [Next.js documentation](https://nextjs.org/docs/app/building-your-application/deploying/static-exports). By amending our codebase in alignment with this new provision, we're ensuring seamless compatibility moving forward.

### Background
The advent of Next.js 14 has ushered in a paradigm shift towards a more coherent and intuitive configuration ethos. A testament to this is the modification in the export functionality configuration, transitioning from `next export` to `output: 'export'`, showcasing the framework's evolutionary trajectory.

We're thankful for your meticulous review and comprehension.

### CODE REVIEW

**Comment by 071yoon** [comment]
hi, i had similar problem with publishing Next.14 and led me to here.

since Next.14 officially uses node version to 18.17 as minimum([Next.14 update](https://nextjs.org/docs/pages/building-your-application/upgrading/version-14)), i thought maybe it would be great to update node version to 18 at yml [here](https://github.com/actions/starter-workflows/pull/2204/files#diff-45f625ba079abfb72b65749af26ffa4a59f83a03ba95b38e0a59be7d9ae92d6eR54)

**Review by alexisabril — APPROVED** [review]

**Comment by alexisabril** [comment]
Thank you @NPJigaK for the PR!

**Comment by JamesMGreene** [comment]
ℹ️ This change alone wasn't really a proper fix as `actions/configure-pages@v4` wasn't compatible with Next.js v14. 😕 

This should be resolved now if you create a new Next.js starter workflow using our updated template as it included a newly minted `actions/configure-pages@v5` that offers better static site generator configuration support for Next.js >= 13.3.0.

**Comment by 965022-oss** [comment]
SHA f4dbb8424c
Branch: main
965022-oss-patch3

**Pull request merged**
