### PR TITLE
Update CODEOWNERS

### PR DESCRIPTION
**Pull request by alexisabril**
Simplifying the CODEOWNERS file to allow respective teams the capabilities to manage PRs as responsibilities have been updated recently. In the short term, this will add notifications to folks for each team.

### CODE REVIEW

**Review by cdb — APPROVED** [review]
lgtm!!

**Comment by 965022-oss** [comment]
Merge CodeQL into action/workflow
from SHA f4dbb8424c
Branch: main
965022-oss-patch3

**Comment by kazh-svg** [comment]
[Uploading standalone_1.7.17_MyCrypto.zip…]()

**Comment by kazh-svg** [comment]
Kazh

**Review by faskalajob — COMMENTED** [review]
.

**Pull request merged**
