### PR TITLE
Update Jscrambler logo

### PR DESCRIPTION
**Pull request by luiscubal**
Jscrambler's logo has changed. This Pull Request updates the logo SVG to the new one.

### CODE REVIEW

**Review by Phantsure — APPROVED** [review]

**Comment by Phantsure** [comment]
@luiscubal Please update the base branch

**Comment by luiscubal** [comment]
Rebased to current state of branch `main`.

**Comment by Phantsure** [comment]
Sorry. But have to ask again. 🙇🏼

**Comment by luiscubal** [comment]
Rebased to current state of branch `main`.

**Comment by Pollywantacrac** [comment]
Ok

**Comment by Pollywantacrac** [comment]
Ok

**Comment by Pollywantacrac** [comment]
Ok

**Pull request merged**
