### PR TITLE
Update nodejs.yml

### PR DESCRIPTION
**Pull request by navneetsharmaui**

### CODE REVIEW

**Comment by navneetsharmaui** [comment]
Testing the GitHub actions

**Comment by Caldas** [comment]
File has been placed at wrong place. Correct *Node* workflow can be found at https://github.com/actions/starter-workflows/blob/master/ci/node.js.yml

**Comment by Caldas** [comment]
I believe this can be closed @navneetsharmaui

**Comment by chumd** [comment]
link  dependencies to be uploaded

**Pull request closed without merging**
