### PR TITLE
dotnet-Workflows: Use latest channel version

### LINKED ISSUE #619: Use latest channel-version of dotnet
Use latest channel-version of dotnet instead of a fixed one.

Over 4 months ago, [actions/setup-dotnet](https://github.com/actions/setup-dotnet) was updated so that you could use the [latest patch](https://github.com/actions/setup-dotnet/pull/82)-version.
However, this was never integrated here...

At the moment dotnet-version [3.1.301](https://github.com/actions/starter-workflows/blob/main/ci/dotnet-core.yml#L19) and [3.1.101](https://github.com/actions/starter-workflows/blob/main/ci/dotnet-core-desktop.yml#L74) 😱  are used.
Both are vulnerable, because there exists security update 3.1.302

Developers will forget to update to the latest version if you don't give them an easy opportunity and by not setting it as default, they will forget it...

### PR DESCRIPTION
**Pull request by litetex**
Fixes #619 

Originally fixed by #620 
This version was updated to .NET 5

### CODE REVIEW

**Comment by andymckay** [comment]
Given that 5.x is not on the runners yet we shouldn't merge this yet. Will likely be a few weeks before its there.

**Comment by andymckay** [comment]
Follow along with the progress here: https://github.com/actions/virtual-environments/issues/1891

**Comment by litetex** [comment]
Resolved merge conflicts

@andymckay 
Do you have any information, if the NET 5 migration is done by now?


> ... Ubuntu images with .NET 5.0 will likely be fully deployed late 16th if there will be no unexpected issues. ...

https://github.com/actions/virtual-environments/issues/1891#issuecomment-744424035

**Comment by joshmgross** [comment]
Based on https://github.com/actions/virtual-environments/issues/1891#issuecomment-748965946, Ubuntu images should have .Net 5.0 now as of December 21st.

**Review by joshmgross — APPROVED** [review]

**Comment by litetex** [comment]
Rebased branch to resolve merge conflicts

**Review by joshmgross — APPROVED** [review]

**Pull request merged**
