### PR TITLE
Maven no transfer progress

### PR DESCRIPTION
**Pull request by sullis**
This repository contains configuration for what users see when they click on the `Actions` tab.

It is not:
* A playground to try out scripts
* A place for you to create a workflow for your repository

---

Thank you for sending in this pull request. Please make sure you take a look at the [contributing file](https://github.com/actions/starter-workflows/blob/main/CONTRIBUTING.md). Here's a few things for you to consider in this pull request.

Please **add to this description** at the bottom :point_down:

- [ ] A good description of the workflow at the bottom of this page.
- [ ] Some links to the language or tool will be nice (unless its really obvious)

In the workflow and properties files:

- [ ] The workflow filename of CI workflows should be the name of the language or platform, in lower case.  Special characters should be removed or replaced with words as appropriate (for example, "dotnet" instead of ".NET").

  The workflow filename of publishing workflows should be the name of the language or platform, in lower case, followed by "-publish".
- [ ] Includes a matching `ci/properties/*.properties.json` file.
- [ ] Use sentence case for the names of workflows and steps, for example "Run tests".
- [ ] The name of CI workflows should only be the name of the language or platform: for example "Go" (not "Go CI" or "Go Build")
- [ ] Include comments in the workflow for any parts that are not obvious or could use clarification.
- [ ] CI workflows should run on `push` to `branches: [ $default-branch ]` and `pull_request` to `branches: [ $default-branch ]`.
- [ ] Packaging workflows should run on `release` with `types: [ created ]`.

Some general notes:

- [ ] This workflow must only use actions that are produced by GitHub, [in the `actions` organization](https://github.com/actions), **or**
- [ ] This workflow must only use actions that are produced by the language or ecosystem that the workflow supports.  These actions must be [published to the GitHub Marketplace](https://github.com/marketplace?type=actions).  Workflows using these actions must reference the action using the full 40 character hash of the action's commit instead of a tag.  Additionally, workflows must include the following comment at the top of the workflow file:
    ```
    # This workflow uses actions that are not certified by GitHub.
    # They are provided by a third-party and are governed by
    # separate terms of service, privacy policy, and support
    # documentation.
    ```
- [ ] This workflow must not send data to any 3rd party service except for the purposes of installing dependencies.
- [ ] This workflow must not use a paid service or product.

### CODE REVIEW

**Comment by Marcono1234** [comment]
If I understand [MNG-6605](https://issues.apache.org/jira/browse/MNG-6605), which added this option, correctly it is only needed when running in interactive mode, but not when running in batch mode (`-B`). So it appears this might be redundant.

**Comment by sullis** [comment]
> If I understand [MNG-6605](https://issues.apache.org/jira/browse/MNG-6605), which added this option, correctly it is only needed when running in interactive mode, but not when running in batch mode (`-B`). So it appears this might be redundant.

Here is an example build:
```
mvn -B clean package
```

Maven's output includes network transfer activity:

Screen Shot 2020-11-25 at 2 22 29 PM

**Review by joshmgross — COMMENTED** [review]
👋  Hey @sullis, could you help me understand why we should add this to the starter workflows?

If there are download issues during the maven step, wouldn't users want to see the transfer progress?

**Comment by Marcono1234** [comment]
> If there are download issues during the maven step, wouldn't users want to see the transfer progress?

Not the original reporter; but it appears that Maven still informs you about download errors with `--no-transfer-progress` (if the download failed for all configured repositories), and even informs you about warnings when the update policy requires checking for new versions (e.g. for snapshot dependencies), but  fetching artifact metadata failed.

So the point of this pull request is likely to reduce the amount of clutter when a project has a lot of dependencies which need to be downloaded.
Though note that when using the GitHub cache action to [cache Maven dependencies](https://github.com/actions/cache/blob/main/examples.md#java---maven), this might only be a problem for the initial build; afterwards the majority (or all) dependencies have already been downloaded.

**Pull request closed without merging**
